### ISSUE TITLE
Does it suppose to work on controller method?

### ISSUE THREAD

**Issue by kuncevic** [dmytropaduchak/nestjs-log#1]
I have a controller method that works welly, however once setting `Log()` getting 404 error

```
  @Log()
  @Post('bla')
  async bla(@Body(PlainToInstancePipe) command: Cmd) { 
     ...
     reuturn myService.myFunc();
  }
  
  ```
  
Status Code: 404
Data: {"message":"Cannot POST /bla","error":"Not Found","statusCode":404}

**Comment by kuncevic** [comment]
well it is does not work with functions either
```
  @Log()
  async myFunc(data: any): Promise<any> { 
    ...
  }
  ```
 errors with 
   
   ```
options?.transform is not a function
[0] TypeError: options?.transform is not a function
```

Any ideas? I am on nest v10

**Comment by dmytropaduchak** [comment]
Sorry, this was one of my test tasks from 2 years ago. I built this model for scheduling jobs and only tested it in that context. It should work with any service methods, but I didn't expect anyone to use it for a controller. 😉

For HTTP-level request and response monitoring, I think it's a good idea to use external services like Datadog, or you could build a custom Nest middleware like this:
```
@Injectable()
export class AppLoggerMiddleware implements NestMiddleware {
  private logger = new Logger('HTTP');

  use(request: Request, response: Response, next: NextFunction): void {
    const { ip, method, path: url } = request;
    const userAgent = request.get('user-agent') || '';

    response.on('close', () => {
      const { statusCode } = response;
      const contentLength = response.get('content-length');

      this.logger.log(
        `${method} ${url} ${statusCode} ${contentLength} - ${userAgent} ${ip}`
      );
    });

    next();
  }
}
```

**Comment by dmytropaduchak** [comment]
> well it is does not work with functions either
> 
> ```
>   @Log()
>   async myFunc(data: any): Promise<any> { 
>     ...
>   }
> ```
> 
> errors with
> 
> ```
> options?.transform is not a function
> [0] TypeError: options?.transform is not a function
> ```
> 
> Any ideas? I am on nest v10

This transform method is just an unfinished version of one of my improvements that I didn't complete and forgot about. Sorry, I don't have the time to fix it right now, but maybe next week I can take a look if it's really important for you. Thanks for your feedback — I really appreciate that someone is trying to use it! 😉
